---
title: "Plots for 'Major differences between bee species, castes, and life stages in the use of a key pesticide target'"
author: "Alicja Witwicka, Federico Lopez"
date: '`r Sys.Date()`'
output:
  github_document:
    toc: yes
  pdf_document: 
    fig_caption: yes
    toc: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Merge all plots created in previous scripts 

# Ratios 
```{r}
# Upload merged data frame
ratios_comparison <- read.csv(
  file.path("plot_data/merged_ratios_plot.csv"),
     header = TRUE,
       stringsAsFactors = TRUE)

level_order <- c("queen_brain", "worker_brain", "thoracic_ganglion", "antenna", "hypopharyngeal_gland", "Malpighian_tubule", "midgut", "muscle", "Nasonov's_gland", "queen_head", "worker_head", "queen_whole_body", "worker_whole_body", "worker_larva", "worker_pupa")

nachrs_order <- c("alpha1", "alpha2", "alpha3", "alpha4", "alpha5", "alpha6", "alpha7", "alpha8", "beta1", "beta2", "alpha9 (only in A. mellifera)")

# Plot data
ratios_plot <- ratios_comparison %>% 
ggplot(aes(x = factor(sample, level = level_order), y = value, fill = factor(nAChRs, level = nachrs_order))) +
  geom_bar(width = 0.7, stat = "identity", position = "fill") +
  xlab("") +
  ylab("Proportion of total nAChRs expression") +
  theme(
    plot.title = element_blank(),
    plot.subtitle = element_text(hjust = 0.5, size = 20, face = "plain"),
    strip.text = element_text(size = 15, face = "italic", hjust = 0.5),
    axis.title = element_text(size = 15),
    axis.text = element_text(size = 15),
    axis.text.x = element_text(size = 15, angle = 65, hjust = 1),
    legend.text = element_text(size = 15),
    legend.title = element_blank(),
    legend.position = "bottom"
  ) +
  facet_grid(~species, labeller = labeller(species = c(amel = "A. mellifera", bter = "B. terrestris")), scales = "free_x", space = "free_x", switch = "x")




```
# Species comparison
```{r}
# Upload .csv for species comparison
species_comparison <- read.csv(
  file.path("plot_data/species_comparison.csv"),
     header = TRUE,
       stringsAsFactors = TRUE)

# Plot data
compr_plot <- ggplot2::ggplot(species_comparison) + geom_abline(colour = "grey", linetype = "dashed") + 
  geom_point(size = 5, stroke = 1.5, aes(x = bter, y = amel, colour=subunit, pch=subunit)) + 
  geom_smooth(formula = y ~ x, colour = "black", size = 0.7, method="lm", se = FALSE, aes(x = bter, y = amel)) + #facet_wrap(~caste, scales = "free_y") +
  xlab("Proportion of nAChRs expression in"~italic("B. terrestris")) +
  ylab("Proportion of nAChRs expression in"~italic("A. mellifera")) +
  theme(axis.title.x = element_text(size=15),
        axis.title.y = element_text(size=15),
        axis.text.x = element_text(size=15),
        axis.text.y = element_text(size=15),
        strip.text = element_text(size = 15, hjust = 0.5),
        legend.text = element_text(size = 15),
        legend.title = element_blank(),
        legend.key.height = unit(1, "cm")) + 
  geom_segment(x = 0, y = 0.4, xend = 0, yend = 0.7, colour = "grey", linetype = "dashed") + scale_shape_manual(values = c(15,16,17,18,19,12,8,9,7,1,3)) +
  facet_wrap(~castes, labeller = labeller(castes = c(queen = "Queens", worker = "Workers")), scales = "free_y")
```
# Total counts
```{r}
# Upload .csv 
total_counts <- read.csv(
  file.path("plot_data/total_counts.csv"),
     header = TRUE,
       stringsAsFactors = TRUE)

species_list <- total_counts %>%
  group_split(species)

amel_level_order <- c("queen_brain", "worker_brain", "thoracic_ganglion", "antenna", "hypopharyngeal_gland", "Malpighian_tubule", "midgut", "muscle", "Nasonov's_gland")

amel_plot <- species_list[[1]] %>% group_by(sample) %>%
       mutate(mean = mean(counts_sume), s_div = sd(counts_sume)) %>%
  ggplot(aes(x = factor(sample, levels = amel_level_order), y = mean)) + 
  geom_bar(stat="identity", position = "dodge", fill = "gray15", colour = "black", width = 0.7) +
  geom_errorbar(aes(ymin = mean-s_div, ymax = mean+s_div), colour = "gray40", width = 0.3) +
  xlab("") +
  ylab("Mean expression of nAChR gene family") +
  theme(
    plot.title = element_blank(),
    plot.subtitle = element_text(hjust = 0.5, size = 20, face = "plain"),
    strip.text = element_text(size = 15, face = "plain", hjust = 0.5),
    axis.title = element_text(size = 15),
    axis.text = element_text(size = 15),
    axis.text.x = element_blank()
  )

bter_level_order <- c("queen_head", "worker_head", "queen_whole_body", "worker_whole_body", "worker_larva", "worker_pupa")

bter_plot <- species_list[[2]] %>% group_by(sample) %>%
       mutate(mean = mean(counts_sume), s_div = sd(counts_sume)) %>%
  ggplot(aes(x = factor(sample, levels = bter_level_order), y = mean)) + 
  geom_bar(stat="identity", position = "dodge", fill = "gray15", colour = "black", width = 0.7) +
  geom_errorbar(aes(ymin = mean-s_div, ymax = mean+s_div), colour = "gray40", width = 0.3) +
  xlab("") +
  ylab("Mean expression of nAChR gene family") +
  theme(
    plot.title = element_blank(),
    plot.subtitle = element_text(hjust = 0.5, size = 20, face = "plain"),
    strip.text = element_text(size = 15, face = "plain", hjust = 0.5),
    axis.title = element_text(size = 15),
    axis.title.y = element_blank(),
    axis.text = element_text(size = 15),
    axis.text.x = element_blank()
  )

```

```{R}
```




